services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "2323:2323"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
  frontend:
    build:
      context: ./language-learning-client
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./language-learning-client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=environment
    command: npm run dev