name: Health Check
on:
  push: 
    branches:
      - main
    pull_request: 
      branches: [main]
        types: [opened, synchronize]
    schedule:
      - cron: "30 12 * * *"
jobs:
  health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://padwhen-learningapp.fly.dev/
          max-attemps: 3
          retry-delay: 5s
