name: Deployment Pipeline
on:
  push:
    branches:
      - main
      - update-workflow-triggers

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: language-learning-client
    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build
        env:
          VITE_GPT_KEY: ${{ secrets.VITE_GPT_KEY }}
          VITE_GOOGLE_KEY: ${{ secrets.VITE_GOOGLE_KEY }}
          VITE_PROMPT_2: ${{ secrets.VITE_PROMPT_2 }}
          VITE_PROMPT_3: ${{ secrets.VITE_PROMPT_3 }}
          VITE_PROMPT_1: ${{ secrets.VITE_PROMPT_1 }}
      - name: Copy built files to backend
        run: cp -r dist ../backend
      - name: Verify copied files
        run: ls -l ../backend/dist
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: |
          cd ../backend
          flyctl deploy --remote-only
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
