name: Deployment Pipeline
on:
  push:
    branches:
      - main
      - update-workflow-triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build
        env:
          VITE_GPT_KEY: ${{ secrets.VITE_GPT_KEY }}
          VITE_GOOGLE_KEY: ${{ secrets.VITE_GOOGLE_KEY }}
          VITE_PROMPT_2: ${{ secrets.VITE_PROMPT_2 }}
          VITE_PROMPT_3: ${{ secrets.VITE_PROMPT_3 }}
          VITE_PROMPT_1: ${{ secrets.VITE_PROMPT_1 }}
      - name: Unit tests
        run: npm run test
  e2e_tests:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies and run e2e tests
        working-directory: language-learning-client
        run: |
          npm install
          npm run test:e2e