name: Deployment Pipeline
on:
  push:
    branches:
      - main
      - update-workflow-triggers
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: language-learning-client
    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build
        env:
          VITE_GPT_KEY: ${{ secrets.VITE_GPT_KEY }}
          VITE_GOOGLE_KEY: ${{ secrets.VITE_GOOGLE_KEY }}
          VITE_PROMPT_2: ${{ secrets.VITE_PROMPT_2 }}
          VITE_PROMPT_3: ${{ secrets.VITE_PROMPT_3 }}
          VITE_PROMPT_1: ${{ secrets.VITE_PROMPT_1 }}
      - name: Unit tests
        run: npm run test
  e2e_tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies and run e2e tests
        working-directory: language-learning-client
        run: |
          npm install
          # Create a temporary script to run e2e tests with 50% threshold
          echo 'const { execSync } = require("child_process");
          try {
            execSync("npm run test:e2e", { stdio: "inherit" });
            process.exit(0);
          } catch (error) {
            const output = error.stdout?.toString() || "";
            const match = output.match(/Tests:\s+(\d+)\s+passed,\s+(\d+)\s+failed/);
            if (match) {
              const passed = parseInt(match[1]);
              const failed = parseInt(match[2]);
              const total = passed + failed;
              const passRate = (passed / total) * 100;
              console.log(`\nTest pass rate: ${passRate.toFixed(1)}%`);
              if (passRate >= 50) {
                console.log("✅ E2E tests passed with >= 50% success rate");
                process.exit(0);
              }
            }
            console.log("❌ E2E tests failed with < 50% success rate");
            process.exit(1);
          }' > check-e2e.js
          node check-e2e.js
  deployed:
    needs: [build, e2e_tests]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build client and copy to backend
        working-directory: language-learning-client
        run: |
          npm install
          npm run build
          cp -r dist ../backend
      - name: Deploy backend
        working-directory: backend
        run: |
          npm install
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
  tag_release:
    needs: [deployed]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
